How to reshape the Array

In [1]:
#Reshape 1D to 2D
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [3]:
newarr = arr.reshape(4,3)

In [4]:
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [5]:
#same array reshape from 1D to 3D
newarrs = arr.reshape(2,3,2)

In [6]:
print(newarrs)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [8]:
arr3 = np.array([1,2,3,4,5,6,7,8])
print(arr3.reshape(2,4).base)

[1 2 3 4 5 6 7 8]


In [9]:
newarr1 = arr3.reshape(2,2,-1)

In [10]:
print(newarr1)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [12]:
arr = np.array([[1,2,3,4],[4,3,2,1]])
newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 4 3 2 1]
