Array Slicing In NumPy using Python

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,6])

In [3]:
arr[1:5]

array([2, 3, 4, 5])

In [4]:
arr[4:]

array([5, 6])

In [5]:
arr[:4]

array([1, 2, 3, 4])

In [6]:
arr[1:4:2]

array([2, 4])

In [7]:
arr[-3:-1]

array([4, 5])

In [8]:
arr[::2]

array([1, 3, 5])

In [9]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [10]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]
