How to get shape of an Array

In [1]:
import numpy as np

In [2]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr.shape)

(2, 5)


In [3]:
arr2 = np.array([1,2,3,4,5],ndmin=5)


In [4]:
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [5]:
print(arr2)

[[[[[1 2 3 4 5]]]]]


In [6]:
print(arr2.shape)

(1, 1, 1, 1, 5)
