NumPy Array Copy vs View

In [1]:
import numpy as np

In [2]:
arr = np.array([1,23,34,55,66])
x = arr.copy()

In [3]:
print(x)

[ 1 23 34 55 66]


In [4]:
arr[0] = 42

In [5]:
print(arr)
print(x)

[42 23 34 55 66]
[ 1 23 34 55 66]


In [8]:
arr1 = np.array([1,2,3,4,5,6,7])


In [9]:
y = arr1.view()

In [10]:
arr1[2] = 34

In [11]:
print(y)

[ 1  2 34  4  5  6  7]


In [12]:
print(arr1)

[ 1  2 34  4  5  6  7]


In [14]:
arr2 = np.array([1,2,3,4,5,6])
z = arr2.view()


In [15]:
z[1] = 16

In [16]:
print(z)

[ 1 16  3  4  5  6]


In [17]:
print(arr2)

[ 1 16  3  4  5  6]


Using "base" we can check that is array owns the data or not.

In [18]:
arr3 = np.array([1,2,3,4,5,5,6,7])
a = arr3.copy()
b = arr3.view()

In [19]:
print(a.base)

None


In [20]:
print(b.base)

[1 2 3 4 5 5 6 7]
