Implementing Data Types in NumPy

In [1]:
import numpy as np

In [2]:
arr = np.array(['apple','banana','cherry'])
print (arr.dtype)

<U6


In [3]:
arr = np.array([1,2,3,4,5], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4' b'5']
|S1


In [4]:
#Create an array with data type 4 bytes integer
arr = np.array([1,2,3,4,5,6] , dtype='i4')
print(arr)
print(arr.dtype)

[1 2 3 4 5 6]
int32


Converting Data Type on Existing Arrays

In [5]:
#Change data type from float to integer by using 'i' as parameter value
arr = np.array([1.1,1.2,1.3,1.4])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 1 1 1]
int32


In [6]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int64


In [7]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True  True  True]
bool


In [8]:
arr = np.array([-1, 0, 1])
newarr = arr.astype(bool)
print(newarr)

[ True False  True]
